### ISSUE TITLE
“ProPresenter Library Wrapper” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by drewterry** [Emmanuel-Croydon/ProPresenter-Library-Wrapper-BASH#1]
After following the installation instructions, I get this error on MacOS.  Possible issues from the MacOS help:

> The app has been modified, and its code does not match the original signed code. The app may be broken or corrupted, or it may have been tampered with. If you think that an app has been damaged or tampered with, you should delete it by dragging it to the Trash.

> Some apps and tools, such as AppleScript or JavaScript applications and some legacy tools, modify themselves after signing. These types of apps cannot be opened unless you override the security settings on your Mac. See Open an app by overriding security settings.

![image](https://user-images.githubusercontent.com/28908820/135124551-e4f2c906-ed63-4bba-a3c3-738a6ded0076.png)

**Comment by Jonathan-Mash** [comment]
Sorry that I haven't responded on this sooner: I've been fairly busy with the prep for Christmas over the last couple of months.

I'm aware of this issue and it's to do with the MacOS security settings not responding well to me keeping the config within the basic application bundle that I've set up or rather, more specifically, to me changing the config file set up in the app bundle as part of the install script.

There is a workaround that I can provide you, which is if you run the appliction bundle before you run the installScript.sh and click 'Allow' in the security settings then the install script will work after that and it all installs in a much happier state.

The real solution to this, though, would be to change how I deal with config and probably to externalise it from the app bundle. I'm actually doing some work on this project in the coming week to allow machines to be designated as ones that only have read-only access to the library, so I'll have a look at it then.

Jonathan

**Comment by Jonathan-Mash** [comment]
Fixed in v7.5
